// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1rhM6ohKrGGAbwHYO0aPWmXtLvFksIs',
    appId: '1:1073384949806:web:4e54ee53b86ca0902db7bf',
    messagingSenderId: '1073384949806',
    projectId: 'dept-74935',
    authDomain: 'dept-74935.firebaseapp.com',
    storageBucket: 'dept-74935.firebasestorage.app',
    measurementId: 'G-L3Q2B4KJWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_D1JbHw2UQGEXkOaSuZpctsuaTLPrg78',
    appId: '1:1073384949806:android:08b1d1a1da4ccc2d2db7bf',
    messagingSenderId: '1073384949806',
    projectId: 'dept-74935',
    storageBucket: 'dept-74935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATFty_CMMdfneKjOGTGpdOV_-aL2c9PVI',
    appId: '1:1073384949806:ios:24d2aa692122e06d2db7bf',
    messagingSenderId: '1073384949806',
    projectId: 'dept-74935',
    storageBucket: 'dept-74935.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATFty_CMMdfneKjOGTGpdOV_-aL2c9PVI',
    appId: '1:1073384949806:ios:24d2aa692122e06d2db7bf',
    messagingSenderId: '1073384949806',
    projectId: 'dept-74935',
    storageBucket: 'dept-74935.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1rhM6ohKrGGAbwHYO0aPWmXtLvFksIs',
    appId: '1:1073384949806:web:e82aac6cd017e8a12db7bf',
    messagingSenderId: '1073384949806',
    projectId: 'dept-74935',
    authDomain: 'dept-74935.firebaseapp.com',
    storageBucket: 'dept-74935.firebasestorage.app',
    measurementId: 'G-0QWMK08M7P',
  );
}
